---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
  namespace: kube-system
spec:
  target:
    name: cloudflare-secrets
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        email: |-
          {{ .email }}
        api-key: |-
          {{ .apikey }}
  data:
    - secretKey: email
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6bf20ac6-c5c5-4c72-96eb-b3f800752799
        property: username
    - secretKey: apikey
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6bf20ac6-c5c5-4c72-96eb-b3f800752799
        property: password

