---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
  namespace: kube-system
spec:
  target:
    name: cloudflare-secrets
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        email: |-
          {{ .email }}
        api-key: |-
          {{ .apikey }}
  data:
    - secretKey: email
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6bf20ac6-c5c5-4c72-96eb-b3f800752799
        property: username
    - secretKey: apikey
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6bf20ac6-c5c5-4c72-96eb-b3f800752799
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traefik-dash-secret
  namespace: kube-system
spec:
  target:
    name: traefik-dash-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        users: |-
          {{ .user }}:{{ .hashedpw }}
  data:
    - secretKey: user
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2df0f056-e9cb-42d0-857f-b3f800774d74
        property: username
    - secretKey: hashedpw
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2df0f056-e9cb-42d0-857f-b3f800774d74
        property: password

