---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: backup/cloudflared
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: backup/traefik
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.rook.io/release
    targetRevision: '1.19.1'
    chart: rook-ceph
    #helm:
    #  valueFiles:
    #    - $values/backup/rook/rook-ceph-operator-values.yaml
  #- repoURL: https://gogs.jibby.org/jhb2345/server
  #  ref: values
  #  targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://charts.rook.io/release
    targetRevision: '1.19.1'
    chart: rook-ceph-cluster
    helm:
      valueFiles:
        - $values/backup/rook/rook-ceph-cluster-values.yaml
      parameters:
        - name: "operatorNamespace"
          value: rook-ceph
  - repoURL: https://gogs.jibby.org/jhb2345/server
    ref: values
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      enabled: true
