---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/infra/cloudflared
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/infra/argocd
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tronbyt
  namespace: argocd
spec:
  destination:
    namespace: tronbyt
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/tronbyt
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: magicmirror
  namespace: argocd
spec:
  destination:
    namespace: magicmirror
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/magicmirror
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/plex
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/jellyfin
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-automation
  namespace: argocd
spec:
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/media-automation
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: argocd/infra/monitoring
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  destination:
    namespace: uptime-kuma
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/infra/uptime-kuma
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: copyparty
  namespace: argocd
spec:
  destination:
    namespace: copyparty
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/copyparty
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gogs
  namespace: argocd
spec:
  destination:
    namespace: gogs
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/gogs
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  destination:
    namespace: homeassistant
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/homeassistant
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/infra/traefik
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upgrade-plan
  namespace: argocd
spec:
  destination:
    namespace: system-upgrade
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/infra/upgrade-plan
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  namespace: argocd
spec:
  destination:
    namespace: miniflux
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/miniflux
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
  namespace: argocd
spec:
  destination:
    namespace: ntfy
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/ntfy
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ooniprobe
  namespace: argocd
spec:
  destination:
    namespace: ooniprobe
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/ooniprobe
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing
  namespace: argocd
spec:
  destination:
    namespace: syncthing
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/syncthing
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seedbox
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/seedbox
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
