---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/infra/cloudflared
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/infra/argocd
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tronbyt
  namespace: argocd
spec:
  destination:
    namespace: tronbyt
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/kiosks/tronbyt
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: magicmirror
  namespace: argocd
spec:
  destination:
    namespace: magicmirror
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/kiosks/magicmirror
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/media/plex
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/media/jellyfin
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-automation
  namespace: argocd
spec:
  destination:
    namespace: plex
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/media/automation
    repoURL: https://gogs.jibby.org/jhb2345/server
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
